<?
header('Content-type: application/json');
session_start();

include "./config/dbinfo.inc.php";

$arrJsonResult = array();
$arrJsonResult["rt_code"] = "0";

if (isset($_POST["guest_name"]) && strlen($_POST["guest_name"]) > 0) {
	// guest login
	$_SESSION['start'] = time(); // Taking now logged in time.
	// Ending a session in 30 minutes from the starting time.
	$_SESSION['expire'] = $_SESSION['start'] + (60 * 60 * 24);
	
	$_SESSION['user_id'] = uniqid("guest_");
	$_SESSION['user_name'] = $_POST["guest_name"];
	
	die(json_encode($arrJsonResult));
}

if (!isset($_POST["id_email"]) || strlen($_POST["id_email"]) <= 0 || !isset($_POST["user_pw"]) || strlen($_POST["user_pw"]) <= 0) {
	$arrJsonResult["rt_code"] = "1000";
	die(json_encode($arrJsonResult));
}

$db = new mysqli($DBHOST, $DBUSER, $DBPASSWD, $DBNAME);
$db->set_charset("utf8");
if ($db->connect_error) {
	$arrJsonResult["rt_code"] = "1000";
	$arrJsonResult["error"] = $db->connect_error;
	die(json_encode($arrJsonResult));
}

$qry = "SELECT * FROM user_basic WHERE id = '".$_POST["id_email"]."' OR email = '".$_POST["id_email"]."'";

$rt = $db->query($qry);

if ($rt->num_rows <= 0) {
	$arrJsonResult["rt_code"] = "2000"; // id or email not correct
	die(json_encode($arrJsonResult));
}

$row = $rt->fetch_array(MYSQLI_ASSOC);
// In addition to incorrect passwords, reject login if password is empty
// (for example, when user is autogenerated for TeachRich.)
if (md5($_POST["user_pw"]) != $row["pw"] || $row["pw"] == '') {
	$arrJsonResult["rt_code"] = "3000"; // pw not correct
	die(json_encode($arrJsonResult));
}

$_SESSION['start'] = time(); // Taking now logged in time.
// Ending a session in 30 minutes from the starting time.
$_SESSION['expire'] = $_SESSION['start'] + (60 * 60 * 24);

if (isset($_POST["keep"]) && $_POST["keep"] == "1") {
	$_SESSION['expire'] = $_SESSION['start'] + (60 * 60 * 24 * 365); // 1년
}

$_SESSION['user_id'] = $row['id'];
$_SESSION['user_name'] = $row['name'];
$_SESSION['user_email'] = $row['email'];
$_SESSION['user_part'] = $row['part'];
$_SESSION['user_dept'] = $row['depart'];
$_SESSION['user_level'] = $row['level'];

$arrJsonResult["part"] = $_SESSION['user_part'];

$rt->close();

$qry = "UPDATE user_basic SET login_datetime = now() WHERE id = '".$_SESSION['user_id']."'";

$db->query($qry);
if ($db->affected_rows <= 0) {
	$arrJsonResult["rt_code"] = "3000";
	$arrJsonResult["error"] = $db->error;
}

$db->close();

die(json_encode($arrJsonResult));
?>
