branch-defaults:
  release:
    environment: release
  develop:
    environment: develop
environment-defaults:
  develop:
    branch: null
    repository: null
global:
  application_name: flipon-api
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
